"""Core data types for the Mantle Alpha Trading Agent.

Port of the NBA bot's TypeScript interfaces to Python dataclasses.
All types are immutable (frozen=True) to follow the immutability principle.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


# ---- Enums ----

class SignalType(str, Enum):
    MOMENTUM = "momentum"
    MEAN_REVERSION = "mean_reversion"
    VOLATILITY_BREAKOUT = "volatility_breakout"
    FUNDING_DIVERGENCE = "funding_divergence"


class Direction(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class TradeStatus(str, Enum):
    DRY_RUN = "dry_run"
    EXECUTED = "executed"
    REJECTED = "rejected"
    FAILED = "failed"


# ---- Market Data ----

@dataclass(frozen=True)
class OHLCV:
    """Single candlestick data point."""
    symbol: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float


@dataclass(frozen=True)
class MarketData:
    """Market data snapshot for a symbol, including derived metrics."""
    symbol: str
    price: float
    timestamp: datetime
    sma_short: float
    sma_long: float
    bb_upper: float
    bb_middle: float
    bb_lower: float
    volume_ma: float
    current_volume: float
    funding_rate: float
    volatility: float


# ---- Signal Types ----

@dataclass(frozen=True)
class Signal:
    """A trading signal generated by a strategy."""
    type: SignalType
    symbol: str
    direction: Direction
    estimated_probability: float
    market_price: float
    edge: float
    confidence: float
    reason: str
    timestamp: datetime


# ---- Risk & Execution ----

@dataclass(frozen=True)
class RiskParams:
    """Configuration for risk management."""
    max_trade_amount: float = 1000.0
    min_edge_threshold: float = 0.02
    min_confidence_threshold: float = 0.3
    max_exposure_per_symbol: float = 5000.0
    kelly_fraction: float = 0.25
    dry_run: bool = True


@dataclass(frozen=True)
class RiskDecision:
    """Result of risk evaluation for a signal."""
    approved: bool
    adjusted_amount: float
    reason: str


@dataclass(frozen=True)
class Trade:
    """A recorded trade (dry-run or executed)."""
    trade_id: str
    signal: Signal
    direction: Direction
    amount: float
    price: float
    status: TradeStatus
    timestamp: datetime
    details: str


# ---- Run Summary ----

@dataclass(frozen=True)
class RunSummary:
    """Summary of a single agent run cycle."""
    timestamp: datetime
    symbols_scanned: int
    signals_generated: list[Signal] = field(default_factory=list)
    signals_rejected: list[Signal] = field(default_factory=list)
    trades_executed: list[Trade] = field(default_factory=list)
    audit_log_path: str = ""
